#!/bin/sh

module="my_cdev"
device="cj"
mode="664"

# install the module
insmod ./${module}.ko 

# find out the major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

echo $major
# create devices
mknod /dev/${device} c $major 0

group="staff"
grep -q '^staff:' /etc/group || group="wheel"

chgrp $group /dev/${device}
chmod $mode  /dev/${device}
