#!/bin/sh

module_fn="my_cdev"
module_name="cj_cdev"
device="cj"
mode="664"

# install the module
insmod ./${module_fn}.ko 

# find out the major number
major=$(awk "\$2 == \"${module_name}\" {print \$1}" /proc/devices)

# create devices
mknod /dev/${device} c ${major} 0

group="staff"
grep -q '^staff:' /etc/group || group="wheel"

chgrp $group /dev/${device}
chmod $mode  /dev/${device}
